env:
  global:
    - RUST_BACKTRACE=1
    - PATH=$PATH:$HOME/.cargo/bin
os:
  - linux
  - osx
  - windows
language: rust
sudo: true
cache:
  cargo: true
before_script:
  - if ! cargo prune --version | grep -q "0.1.8"; then
      cargo install cargo-prune --vers="0.1.8" --force;
    fi
  - rustup component add rustfmt clippy
  - git submodule update --init --recursive
script:
  - cargo fmt -- --check &&
    cargo test --verbose --release &&
    cargo clippy --verbose --release --all-targets
before_cache:
  - cargo prune
